# PHP CircleCI configuration file
# Runs tests against configured scratch organization in environment variables
version: 2.1
orbs:
  semantic-release: proxyco/semantic-release@3.0.0
jobs:
  release:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - run: sudo npm install -g @semantic-release/git semantic-release
      - run: sudo cp .circleci/package.json . # this is a placeholder package just to make releases happen
      - semantic-release/release
  test:
    docker:
      - image: cimg/php:8.0
    steps:
      - checkout
      # composer cache
      - restore_cache:
          keys:
            # "composer.json" can be used if "composer.json"
            # is not committed to the repository.
            - composer-v1-{{ checksum "composer.lock" }}
            # fallback to using the latest cache if no exact match is found
            - composer-v1-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - run: touch .env
      - run: ./vendor/bin/pest

workflows:
  version: 2
  workflow:
    jobs:
      - test
      - release:
          requires:
            - test
          filters:
            branches:
              only:
                - main